language: node_js
node_js:
  - "8"
addons:
  postgresql: "9.5"
install:
  - yarn
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
before_script:
  - cp .env.example .env
  - psql -U postgres -c "create extension postgis"
  - yarn test-setup
script:
  - yarn test
after_script:
  - yarn test-cleanup
